[package]
name = "flox-wasm"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[build]
target = "wasm32-unknown-unknown"

[dependencies]
flox-core    = { path = "../flox-core"}
wasm-bindgen = "0.2.93"
